// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthHistoryDataAugmentation9 tapi eth history data augmentation9
// swagger:model tapi.eth.HistoryDataAugmentation9
type TapiEthHistoryDataAugmentation9 struct {

	// none
	EthProActive1LmSourcePerformanceData TapiEthEthProActive1LmSourcePerformanceData `json:"eth-pro-active-1-lm-source-performance-data,omitempty"`
}

// Validate validates this tapi eth history data augmentation9
func (m *TapiEthHistoryDataAugmentation9) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthHistoryDataAugmentation9) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthHistoryDataAugmentation9) UnmarshalBinary(b []byte) error {
	var res TapiEthHistoryDataAugmentation9
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
