// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPhotonicMediaNodeEdgePointAugmentation1 tapi photonic media node edge point augmentation1
// swagger:model tapi.photonic.media.NodeEdgePointAugmentation1
type TapiPhotonicMediaNodeEdgePointAugmentation1 struct {

	// none
	MediaChannelNodeEdgePointSpec *TapiPhotonicMediaMediaChannelNodeEdgePointSpec `json:"media-channel-node-edge-point-spec,omitempty"`
}

// Validate validates this tapi photonic media node edge point augmentation1
func (m *TapiPhotonicMediaNodeEdgePointAugmentation1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMediaChannelNodeEdgePointSpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPhotonicMediaNodeEdgePointAugmentation1) validateMediaChannelNodeEdgePointSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.MediaChannelNodeEdgePointSpec) { // not required
		return nil
	}

	if m.MediaChannelNodeEdgePointSpec != nil {
		if err := m.MediaChannelNodeEdgePointSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("media-channel-node-edge-point-spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPhotonicMediaNodeEdgePointAugmentation1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPhotonicMediaNodeEdgePointAugmentation1) UnmarshalBinary(b []byte) error {
	var res TapiPhotonicMediaNodeEdgePointAugmentation1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
