// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthLldpChassisIDSubtype tapi eth lldp chassis Id subtype
// swagger:model tapi.eth.LldpChassisIdSubtype
type TapiEthLldpChassisIDSubtype struct {

	// String length '0..32'
	//                 Represents a chassis identifier based on the value of entPhysicalAlias object (defined in IETF RFC 2737) for a chassis component (i.e., an entPhysicalClass value of chassis(3)).
	ChassisComponent string `json:"chassis-component,omitempty"`

	// String length '0..64'
	//                 Represents a chassis identifier based on the value of ifAlias object (defined in IETF RFC 2863) for an interface on the containing chassis.
	InterfaceAlias string `json:"interface-alias,omitempty"`

	// Represents a chassis identifier based on the value of ifName object (defined in IETF RFC 2863) for an interface on the containing chassis.
	InterfaceName string `json:"interface-name,omitempty"`

	// Represents a chassis identifier based on a locally defined value.
	Local string `json:"local,omitempty"`

	// Represents a chassis identifier based on the value of a unicast source address (encoded in network byte order and IEEE 802.3 canonical bit order), of a port on the containing chassis as defined in IEEE Std 802-2001.
	MacAddress string `json:"mac-address,omitempty"`

	// Octet string that identifies a particular network address family and an associated network address that are encoded in network octet order.
	//                 An IP address, for example, would be encoded with the first octet containing the IANA Address Family Numbers enumeration value for the specific address type and octets 2 through n containing the address value.
	NetworkAddress string `json:"network-address,omitempty"`

	// String length '0..32'
	//                 Represents a chassis identifier based on the value of entPhysicalAlias object (defined in IETF RFC 2737) for a port or backplane component (i.e., entPhysicalClass value of port(10) or backplane(4)), within the containing chassis.
	PortComponent string `json:"port-component,omitempty"`
}

// Validate validates this tapi eth lldp chassis Id subtype
func (m *TapiEthLldpChassisIDSubtype) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthLldpChassisIDSubtype) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthLldpChassisIDSubtype) UnmarshalBinary(b []byte) error {
	var res TapiEthLldpChassisIDSubtype
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
