// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiPhotonicMediaSelectedModulation tapi photonic media selected modulation
// swagger:model tapi.photonic.media.SelectedModulation
type TapiPhotonicMediaSelectedModulation string

const (

	// TapiPhotonicMediaSelectedModulationRZ captures enum value "RZ"
	TapiPhotonicMediaSelectedModulationRZ TapiPhotonicMediaSelectedModulation = "RZ"

	// TapiPhotonicMediaSelectedModulationNRZ captures enum value "NRZ"
	TapiPhotonicMediaSelectedModulationNRZ TapiPhotonicMediaSelectedModulation = "NRZ"

	// TapiPhotonicMediaSelectedModulationBPSK captures enum value "BPSK"
	TapiPhotonicMediaSelectedModulationBPSK TapiPhotonicMediaSelectedModulation = "BPSK"

	// TapiPhotonicMediaSelectedModulationDPSK captures enum value "DPSK"
	TapiPhotonicMediaSelectedModulationDPSK TapiPhotonicMediaSelectedModulation = "DPSK"

	// TapiPhotonicMediaSelectedModulationQPSK captures enum value "QPSK"
	TapiPhotonicMediaSelectedModulationQPSK TapiPhotonicMediaSelectedModulation = "QPSK"

	// TapiPhotonicMediaSelectedModulationNr8QAM captures enum value "8QAM"
	TapiPhotonicMediaSelectedModulationNr8QAM TapiPhotonicMediaSelectedModulation = "8QAM"

	// TapiPhotonicMediaSelectedModulationNr16QAM captures enum value "16QAM"
	TapiPhotonicMediaSelectedModulationNr16QAM TapiPhotonicMediaSelectedModulation = "16QAM"

	// TapiPhotonicMediaSelectedModulationPAM4 captures enum value "PAM4"
	TapiPhotonicMediaSelectedModulationPAM4 TapiPhotonicMediaSelectedModulation = "PAM4"

	// TapiPhotonicMediaSelectedModulationPAM8 captures enum value "PAM8"
	TapiPhotonicMediaSelectedModulationPAM8 TapiPhotonicMediaSelectedModulation = "PAM8"

	// TapiPhotonicMediaSelectedModulationUNDEFINED captures enum value "UNDEFINED"
	TapiPhotonicMediaSelectedModulationUNDEFINED TapiPhotonicMediaSelectedModulation = "UNDEFINED"
)

// for schema
var tapiPhotonicMediaSelectedModulationEnum []interface{}

func init() {
	var res []TapiPhotonicMediaSelectedModulation
	if err := json.Unmarshal([]byte(`["RZ","NRZ","BPSK","DPSK","QPSK","8QAM","16QAM","PAM4","PAM8","UNDEFINED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiPhotonicMediaSelectedModulationEnum = append(tapiPhotonicMediaSelectedModulationEnum, v)
	}
}

func (m TapiPhotonicMediaSelectedModulation) validateTapiPhotonicMediaSelectedModulationEnum(path, location string, value TapiPhotonicMediaSelectedModulation) error {
	if err := validate.Enum(path, location, value, tapiPhotonicMediaSelectedModulationEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi photonic media selected modulation
func (m TapiPhotonicMediaSelectedModulation) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiPhotonicMediaSelectedModulationEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
