// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEndPointAugmentation2 tapi eth end point augmentation2
// swagger:model tapi.eth.EndPointAugmentation2
type TapiEthEndPointAugmentation2 struct {

	// none
	EthConnectivityServiceEndPointSpec *TapiEthEthConnectivityServiceEndPointSpec `json:"eth-connectivity-service-end-point-spec,omitempty"`
}

// Validate validates this tapi eth end point augmentation2
func (m *TapiEthEndPointAugmentation2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthConnectivityServiceEndPointSpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEndPointAugmentation2) validateEthConnectivityServiceEndPointSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.EthConnectivityServiceEndPointSpec) { // not required
		return nil
	}

	if m.EthConnectivityServiceEndPointSpec != nil {
		if err := m.EthConnectivityServiceEndPointSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-connectivity-service-end-point-spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEndPointAugmentation2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEndPointAugmentation2) UnmarshalBinary(b []byte) error {
	var res TapiEthEndPointAugmentation2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
