// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthEtyTerminationCommonPac tapi eth ety termination common pac
// swagger:model tapi.eth.EtyTerminationCommonPac
type TapiEthEtyTerminationCommonPac struct {

	// This attribute indicates whether Forced Transmitter Shutdown (FTS) is enabled or not. It models the ETYn_TT_So_MI_FTSEnable information.
	IsFtsEnabled *bool `json:"is-fts-enabled,omitempty"`

	// This attribute identifies whether the Transmit Pause process is enabled or not. It models the MI_TxPauseEnable defined in G.8021.
	IsTxPauseEnabled *bool `json:"is-tx-pause-enabled,omitempty"`
}

// Validate validates this tapi eth ety termination common pac
func (m *TapiEthEtyTerminationCommonPac) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEtyTerminationCommonPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEtyTerminationCommonPac) UnmarshalBinary(b []byte) error {
	var res TapiEthEtyTerminationCommonPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
