// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEquipmentGetdevicelistOutput tapi equipment getdevicelist output
// swagger:model tapi.equipment.getdevicelist.Output
type TapiEquipmentGetdevicelistOutput struct {

	// none
	Device []*TapiEquipmentDevice `json:"device"`
}

// Validate validates this tapi equipment getdevicelist output
func (m *TapiEquipmentGetdevicelistOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDevice(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEquipmentGetdevicelistOutput) validateDevice(formats strfmt.Registry) error {

	if swag.IsZero(m.Device) { // not required
		return nil
	}

	for i := 0; i < len(m.Device); i++ {
		if swag.IsZero(m.Device[i]) { // not required
			continue
		}

		if m.Device[i] != nil {
			if err := m.Device[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("device" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentGetdevicelistOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentGetdevicelistOutput) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentGetdevicelistOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
