// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityNodeEdgePointAugmentation3 tapi connectivity node edge point augmentation3
// swagger:model tapi.connectivity.NodeEdgePointAugmentation3
type TapiConnectivityNodeEdgePointAugmentation3 struct {

	// none
	CepList *TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList `json:"cep-list,omitempty"`
}

// Validate validates this tapi connectivity node edge point augmentation3
func (m *TapiConnectivityNodeEdgePointAugmentation3) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCepList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityNodeEdgePointAugmentation3) validateCepList(formats strfmt.Registry) error {

	if swag.IsZero(m.CepList) { // not required
		return nil
	}

	if m.CepList != nil {
		if err := m.CepList.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cep-list")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityNodeEdgePointAugmentation3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityNodeEdgePointAugmentation3) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityNodeEdgePointAugmentation3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
