// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamCurrentdataHistoryData tapi oam currentdata history data
// swagger:model tapi.oam.currentdata.HistoryData
type TapiOamCurrentdataHistoryData struct {
	TapiEthHistoryDataAugmentation1

	TapiEthHistoryDataAugmentation10

	TapiEthHistoryDataAugmentation11

	TapiEthHistoryDataAugmentation12

	TapiEthHistoryDataAugmentation2

	TapiEthHistoryDataAugmentation3

	TapiEthHistoryDataAugmentation4

	TapiEthHistoryDataAugmentation5

	TapiEthHistoryDataAugmentation6

	TapiEthHistoryDataAugmentation7

	TapiEthHistoryDataAugmentation8

	TapiEthHistoryDataAugmentation9

	TapiOamHistoryData
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiOamCurrentdataHistoryData) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiEthHistoryDataAugmentation1
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation1 = aO0

	// AO1
	var aO1 TapiEthHistoryDataAugmentation10
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation10 = aO1

	// AO2
	var aO2 TapiEthHistoryDataAugmentation11
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation11 = aO2

	// AO3
	var aO3 TapiEthHistoryDataAugmentation12
	if err := swag.ReadJSON(raw, &aO3); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation12 = aO3

	// AO4
	var aO4 TapiEthHistoryDataAugmentation2
	if err := swag.ReadJSON(raw, &aO4); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation2 = aO4

	// AO5
	var aO5 TapiEthHistoryDataAugmentation3
	if err := swag.ReadJSON(raw, &aO5); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation3 = aO5

	// AO6
	var aO6 TapiEthHistoryDataAugmentation4
	if err := swag.ReadJSON(raw, &aO6); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation4 = aO6

	// AO7
	var aO7 TapiEthHistoryDataAugmentation5
	if err := swag.ReadJSON(raw, &aO7); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation5 = aO7

	// AO8
	var aO8 TapiEthHistoryDataAugmentation6
	if err := swag.ReadJSON(raw, &aO8); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation6 = aO8

	// AO9
	var aO9 TapiEthHistoryDataAugmentation7
	if err := swag.ReadJSON(raw, &aO9); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation7 = aO9

	// AO10
	var aO10 TapiEthHistoryDataAugmentation8
	if err := swag.ReadJSON(raw, &aO10); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation8 = aO10

	// AO11
	var aO11 TapiEthHistoryDataAugmentation9
	if err := swag.ReadJSON(raw, &aO11); err != nil {
		return err
	}
	m.TapiEthHistoryDataAugmentation9 = aO11

	// AO12
	var aO12 TapiOamHistoryData
	if err := swag.ReadJSON(raw, &aO12); err != nil {
		return err
	}
	m.TapiOamHistoryData = aO12

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiOamCurrentdataHistoryData) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 13)

	aO0, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation10)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation11)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)

	aO3, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation12)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO3)

	aO4, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO4)

	aO5, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation3)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO5)

	aO6, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation4)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO6)

	aO7, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation5)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO7)

	aO8, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation6)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO8)

	aO9, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation7)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO9)

	aO10, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation8)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO10)

	aO11, err := swag.WriteJSON(m.TapiEthHistoryDataAugmentation9)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO11)

	aO12, err := swag.WriteJSON(m.TapiOamHistoryData)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO12)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi oam currentdata history data
func (m *TapiOamCurrentdataHistoryData) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiEthHistoryDataAugmentation1
	if err := m.TapiEthHistoryDataAugmentation1.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation10
	if err := m.TapiEthHistoryDataAugmentation10.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation11
	if err := m.TapiEthHistoryDataAugmentation11.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation12
	if err := m.TapiEthHistoryDataAugmentation12.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation2
	if err := m.TapiEthHistoryDataAugmentation2.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation3
	if err := m.TapiEthHistoryDataAugmentation3.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation4
	if err := m.TapiEthHistoryDataAugmentation4.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation5
	if err := m.TapiEthHistoryDataAugmentation5.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation6
	if err := m.TapiEthHistoryDataAugmentation6.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation7
	if err := m.TapiEthHistoryDataAugmentation7.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation8
	if err := m.TapiEthHistoryDataAugmentation8.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthHistoryDataAugmentation9
	if err := m.TapiEthHistoryDataAugmentation9.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiOamHistoryData
	if err := m.TapiOamHistoryData.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamCurrentdataHistoryData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamCurrentdataHistoryData) UnmarshalBinary(b []byte) error {
	var res TapiOamCurrentdataHistoryData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
