// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthInputAugmentation2 tapi eth input augmentation2
// swagger:model tapi.eth.InputAugmentation2
type TapiEthInputAugmentation2 struct {

	// none
	EthLoopbackJob *TapiEthEthLoopbackJob `json:"eth-loopback-job,omitempty"`
}

// Validate validates this tapi eth input augmentation2
func (m *TapiEthInputAugmentation2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthLoopbackJob(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthInputAugmentation2) validateEthLoopbackJob(formats strfmt.Registry) error {

	if swag.IsZero(m.EthLoopbackJob) { // not required
		return nil
	}

	if m.EthLoopbackJob != nil {
		if err := m.EthLoopbackJob.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-loopback-job")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthInputAugmentation2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthInputAugmentation2) UnmarshalBinary(b []byte) error {
	var res TapiEthInputAugmentation2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
