// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPhotonicMediaConnectionEndPointAugmentation2 tapi photonic media connection end point augmentation2
// swagger:model tapi.photonic.media.ConnectionEndPointAugmentation2
type TapiPhotonicMediaConnectionEndPointAugmentation2 struct {

	// none
	OtsiConnectionEndPointSpec *TapiPhotonicMediaOtsiConnectionEndPointSpec `json:"otsi-connection-end-point-spec,omitempty"`
}

// Validate validates this tapi photonic media connection end point augmentation2
func (m *TapiPhotonicMediaConnectionEndPointAugmentation2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOtsiConnectionEndPointSpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPhotonicMediaConnectionEndPointAugmentation2) validateOtsiConnectionEndPointSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.OtsiConnectionEndPointSpec) { // not required
		return nil
	}

	if m.OtsiConnectionEndPointSpec != nil {
		if err := m.OtsiConnectionEndPointSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("otsi-connection-end-point-spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPhotonicMediaConnectionEndPointAugmentation2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPhotonicMediaConnectionEndPointAugmentation2) UnmarshalBinary(b []byte) error {
	var res TapiPhotonicMediaConnectionEndPointAugmentation2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
