// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPhotonicMediaSipAugmentation3 tapi photonic media sip augmentation3
// swagger:model tapi.photonic.media.SipAugmentation3
type TapiPhotonicMediaSipAugmentation3 struct {

	// none
	MediaChannelServiceInterfacePointSpec *TapiPhotonicMediaMediaChannelServiceInterfacePointSpec `json:"media-channel-service-interface-point-spec,omitempty"`
}

// Validate validates this tapi photonic media sip augmentation3
func (m *TapiPhotonicMediaSipAugmentation3) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMediaChannelServiceInterfacePointSpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPhotonicMediaSipAugmentation3) validateMediaChannelServiceInterfacePointSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.MediaChannelServiceInterfacePointSpec) { // not required
		return nil
	}

	if m.MediaChannelServiceInterfacePointSpec != nil {
		if err := m.MediaChannelServiceInterfacePointSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("media-channel-service-interface-point-spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPhotonicMediaSipAugmentation3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPhotonicMediaSipAugmentation3) UnmarshalBinary(b []byte) error {
	var res TapiPhotonicMediaSipAugmentation3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
