// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthMegAugmentation2 tapi eth meg augmentation2
// swagger:model tapi.eth.MegAugmentation2
type TapiEthMegAugmentation2 struct {

	// none
	EthMegSpec *TapiEthEthMegSpec `json:"eth-meg-spec,omitempty"`
}

// Validate validates this tapi eth meg augmentation2
func (m *TapiEthMegAugmentation2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthMegSpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthMegAugmentation2) validateEthMegSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.EthMegSpec) { // not required
		return nil
	}

	if m.EthMegSpec != nil {
		if err := m.EthMegSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-meg-spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthMegAugmentation2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthMegAugmentation2) UnmarshalBinary(b []byte) error {
	var res TapiEthMegAugmentation2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
