// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEquipmentAccessPortRef tapi equipment access port ref
// swagger:model tapi.equipment.AccessPortRef
type TapiEquipmentAccessPortRef struct {
	TapiEquipmentDeviceRef

	// none
	AccessPortUUID string `json:"access-port-uuid,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiEquipmentAccessPortRef) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiEquipmentDeviceRef
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiEquipmentDeviceRef = aO0

	// AO1
	var dataAO1 struct {
		AccessPortUUID string `json:"access-port-uuid,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.AccessPortUUID = dataAO1.AccessPortUUID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiEquipmentAccessPortRef) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.TapiEquipmentDeviceRef)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		AccessPortUUID string `json:"access-port-uuid,omitempty"`
	}

	dataAO1.AccessPortUUID = m.AccessPortUUID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi equipment access port ref
func (m *TapiEquipmentAccessPortRef) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiEquipmentDeviceRef
	if err := m.TapiEquipmentDeviceRef.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentAccessPortRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentAccessPortRef) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentAccessPortRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
