// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityCreateconnectivityserviceInputEndPoint tapi connectivity createconnectivityservice input end point
// swagger:model tapi.connectivity.createconnectivityservice.input.EndPoint
type TapiConnectivityCreateconnectivityserviceInputEndPoint struct {
	TapiConnectivityConnectivityServiceEndPoint

	TapiEthEndPointAugmentation3

	TapiPhotonicMediaEndPointAugmentation1

	TapiPhotonicMediaEndPointAugmentation2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiConnectivityCreateconnectivityserviceInputEndPoint) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiConnectivityConnectivityServiceEndPoint
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiConnectivityConnectivityServiceEndPoint = aO0

	// AO1
	var aO1 TapiEthEndPointAugmentation3
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.TapiEthEndPointAugmentation3 = aO1

	// AO2
	var aO2 TapiPhotonicMediaEndPointAugmentation1
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.TapiPhotonicMediaEndPointAugmentation1 = aO2

	// AO3
	var aO3 TapiPhotonicMediaEndPointAugmentation2
	if err := swag.ReadJSON(raw, &aO3); err != nil {
		return err
	}
	m.TapiPhotonicMediaEndPointAugmentation2 = aO3

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiConnectivityCreateconnectivityserviceInputEndPoint) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 4)

	aO0, err := swag.WriteJSON(m.TapiConnectivityConnectivityServiceEndPoint)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.TapiEthEndPointAugmentation3)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.TapiPhotonicMediaEndPointAugmentation1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)

	aO3, err := swag.WriteJSON(m.TapiPhotonicMediaEndPointAugmentation2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO3)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi connectivity createconnectivityservice input end point
func (m *TapiConnectivityCreateconnectivityserviceInputEndPoint) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiConnectivityConnectivityServiceEndPoint
	if err := m.TapiConnectivityConnectivityServiceEndPoint.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthEndPointAugmentation3
	if err := m.TapiEthEndPointAugmentation3.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiPhotonicMediaEndPointAugmentation1
	if err := m.TapiPhotonicMediaEndPointAugmentation1.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiPhotonicMediaEndPointAugmentation2
	if err := m.TapiPhotonicMediaEndPointAugmentation2.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityCreateconnectivityserviceInputEndPoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityCreateconnectivityserviceInputEndPoint) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityCreateconnectivityserviceInputEndPoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
