// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthServiceAugmentation1 tapi eth service augmentation1
// swagger:model tapi.eth.ServiceAugmentation1
type TapiEthServiceAugmentation1 struct {

	// none
	EthConnectivityService TapiEthEthConnectivityService `json:"eth-connectivity-service,omitempty"`
}

// Validate validates this tapi eth service augmentation1
func (m *TapiEthServiceAugmentation1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthServiceAugmentation1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthServiceAugmentation1) UnmarshalBinary(b []byte) error {
	var res TapiEthServiceAugmentation1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
