// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiConnectivityGetconnectiondetailsInput tapi connectivity getconnectiondetails input
// swagger:model tapi.connectivity.getconnectiondetails.Input
type TapiConnectivityGetconnectiondetailsInput struct {

	// none
	ConnectionIDOrName string `json:"connection-id-or-name,omitempty"`
}

// Validate validates this tapi connectivity getconnectiondetails input
func (m *TapiConnectivityGetconnectiondetailsInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityGetconnectiondetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityGetconnectiondetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityGetconnectiondetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
