// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamMepMipList tapi oam mep mip list
// swagger:model tapi.oam.MepMipList
type TapiOamMepMipList struct {

	// none
	Mep []*TapiOamMepRef `json:"mep"`

	// none
	Mip []*TapiOamMipRef `json:"mip"`
}

// Validate validates this tapi oam mep mip list
func (m *TapiOamMepMipList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMep(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMip(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamMepMipList) validateMep(formats strfmt.Registry) error {

	if swag.IsZero(m.Mep) { // not required
		return nil
	}

	for i := 0; i < len(m.Mep); i++ {
		if swag.IsZero(m.Mep[i]) { // not required
			continue
		}

		if m.Mep[i] != nil {
			if err := m.Mep[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mep" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiOamMepMipList) validateMip(formats strfmt.Registry) error {

	if swag.IsZero(m.Mip) { // not required
		return nil
	}

	for i := 0; i < len(m.Mip); i++ {
		if swag.IsZero(m.Mip[i]) { // not required
			continue
		}

		if m.Mip[i] != nil {
			if err := m.Mip[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mip" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamMepMipList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamMepMipList) UnmarshalBinary(b []byte) error {
	var res TapiOamMepMipList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
