// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthProActiveDmPerformanceData tapi eth eth pro active dm performance data
// swagger:model tapi.eth.EthProActiveDmPerformanceData
type TapiEthEthProActiveDmPerformanceData struct {

	// This attribute contains the statistical bidirectional performnace parameters.
	StatisticalBiDirDmParameters *TapiEthStatisticalDmPerformanceParameters `json:"statistical-bi-dir-dm-parameters,omitempty"`

	// This attribute contains the statistical far end performnace parameters.
	StatisticalFarEndDmParameters *TapiEthStatisticalDmPerformanceParameters `json:"statistical-far-end-dm-parameters,omitempty"`

	// This attribute contains the statistical near end performnace parameters.
	StatisticalNearEndDmParameters *TapiEthStatisticalDmPerformanceParameters `json:"statistical-near-end-dm-parameters,omitempty"`
}

// Validate validates this tapi eth eth pro active dm performance data
func (m *TapiEthEthProActiveDmPerformanceData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatisticalBiDirDmParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatisticalFarEndDmParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatisticalNearEndDmParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthProActiveDmPerformanceData) validateStatisticalBiDirDmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.StatisticalBiDirDmParameters) { // not required
		return nil
	}

	if m.StatisticalBiDirDmParameters != nil {
		if err := m.StatisticalBiDirDmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("statistical-bi-dir-dm-parameters")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthProActiveDmPerformanceData) validateStatisticalFarEndDmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.StatisticalFarEndDmParameters) { // not required
		return nil
	}

	if m.StatisticalFarEndDmParameters != nil {
		if err := m.StatisticalFarEndDmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("statistical-far-end-dm-parameters")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthProActiveDmPerformanceData) validateStatisticalNearEndDmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.StatisticalNearEndDmParameters) { // not required
		return nil
	}

	if m.StatisticalNearEndDmParameters != nil {
		if err := m.StatisticalNearEndDmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("statistical-near-end-dm-parameters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthProActiveDmPerformanceData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthProActiveDmPerformanceData) UnmarshalBinary(b []byte) error {
	var res TapiEthEthProActiveDmPerformanceData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
