// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamCreateoamserviceInput tapi oam createoamservice input
// swagger:model tapi.oam.createoamservice.Input
type TapiOamCreateoamserviceInput struct {

	// none
	LayerProtocolName TapiCommonLayerProtocolName `json:"layer-protocol-name,omitempty"`

	// none
	OamServicePoint []*TapiOamCreateoamserviceInputOamServicePoint `json:"oam-service-point"`

	// none
	State TapiCommonAdministrativeState `json:"state,omitempty"`
}

// Validate validates this tapi oam createoamservice input
func (m *TapiOamCreateoamserviceInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLayerProtocolName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOamServicePoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamCreateoamserviceInput) validateLayerProtocolName(formats strfmt.Registry) error {

	if swag.IsZero(m.LayerProtocolName) { // not required
		return nil
	}

	if err := m.LayerProtocolName.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("layer-protocol-name")
		}
		return err
	}

	return nil
}

func (m *TapiOamCreateoamserviceInput) validateOamServicePoint(formats strfmt.Registry) error {

	if swag.IsZero(m.OamServicePoint) { // not required
		return nil
	}

	for i := 0; i < len(m.OamServicePoint); i++ {
		if swag.IsZero(m.OamServicePoint[i]) { // not required
			continue
		}

		if m.OamServicePoint[i] != nil {
			if err := m.OamServicePoint[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("oam-service-point" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiOamCreateoamserviceInput) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if err := m.State.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamCreateoamserviceInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamCreateoamserviceInput) UnmarshalBinary(b []byte) error {
	var res TapiOamCreateoamserviceInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
