// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityContextAugmentation6 tapi connectivity context augmentation6
// swagger:model tapi.connectivity.ContextAugmentation6
type TapiConnectivityContextAugmentation6 struct {

	// Augments the base TAPI Context with ConnectivityService information
	ConnectivityContext *TapiConnectivityContextConnectivityContext `json:"connectivity-context,omitempty"`
}

// Validate validates this tapi connectivity context augmentation6
func (m *TapiConnectivityContextAugmentation6) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectivityContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityContextAugmentation6) validateConnectivityContext(formats strfmt.Registry) error {

	if swag.IsZero(m.ConnectivityContext) { // not required
		return nil
	}

	if m.ConnectivityContext != nil {
		if err := m.ConnectivityContext.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("connectivity-context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityContextAugmentation6) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityContextAugmentation6) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityContextAugmentation6
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
