// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiNotificationContextNotificationContext tapi notification context notification context
// swagger:model tapi.notification.context.NotificationContext
type TapiNotificationContextNotificationContext struct {

	// none
	NotifSubscription []*TapiNotificationNotificationSubscriptionService `json:"notif-subscription"`

	// none
	Notification []*TapiNotificationNotificationcontextNotification `json:"notification"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiNotificationContextNotificationContext) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		NotifSubscription []*TapiNotificationNotificationSubscriptionService `json:"notif-subscription"`

		Notification []*TapiNotificationNotificationcontextNotification `json:"notification"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.NotifSubscription = dataAO0.NotifSubscription

	m.Notification = dataAO0.Notification

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiNotificationContextNotificationContext) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		NotifSubscription []*TapiNotificationNotificationSubscriptionService `json:"notif-subscription"`

		Notification []*TapiNotificationNotificationcontextNotification `json:"notification"`
	}

	dataAO0.NotifSubscription = m.NotifSubscription

	dataAO0.Notification = m.Notification

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi notification context notification context
func (m *TapiNotificationContextNotificationContext) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNotifSubscription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotification(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiNotificationContextNotificationContext) validateNotifSubscription(formats strfmt.Registry) error {

	if swag.IsZero(m.NotifSubscription) { // not required
		return nil
	}

	for i := 0; i < len(m.NotifSubscription); i++ {
		if swag.IsZero(m.NotifSubscription[i]) { // not required
			continue
		}

		if m.NotifSubscription[i] != nil {
			if err := m.NotifSubscription[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notif-subscription" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiNotificationContextNotificationContext) validateNotification(formats strfmt.Registry) error {

	if swag.IsZero(m.Notification) { // not required
		return nil
	}

	for i := 0; i < len(m.Notification); i++ {
		if swag.IsZero(m.Notification[i]) { // not required
			continue
		}

		if m.Notification[i] != nil {
			if err := m.Notification[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notification" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiNotificationContextNotificationContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNotificationContextNotificationContext) UnmarshalBinary(b []byte) error {
	var res TapiNotificationContextNotificationContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
