// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthCtpPac tapi eth eth ctp pac
// swagger:model tapi.eth.EthCtpPac
type TapiEthEthCtpPac struct {

	// See 802.1AX:
	//                 The current operational value of the Key for the Aggregator. The administrative Key value may differ from the operational Key value for the reasons discussed in 5.6.2.
	//                 The meaning of particular Key values is of local significance.
	//                 range of type : 16 bit
	ActorOperKey int32 `json:"actor-oper-key,omitempty"`

	// See 802.1AX:
	//                 A MAC address used as a unique identifier for the System that contains this Aggregator.
	ActorSystemID string `json:"actor-system-id,omitempty"`

	// See 802.1AX:
	//                 Indicating the priority associated with the Actors System ID.
	//                 range of type : 2-octet
	ActorSystemPriority int32 `json:"actor-system-priority,omitempty"`

	// See 802.1AX:
	//                 The current data rate, in bits per second, of the aggregate link. The value is calculated as N times the data rate of a single link in the aggregation, where N is the number of active links.
	DataRate int32 `json:"data-rate,omitempty"`

	// none
	EthCtpCommonPac *TapiEthEthCtpCommonPac `json:"eth-ctp-common-pac,omitempty"`

	// See 802.1AX:
	//                 The current operational value of the Key for the Aggregators current protocol Partner. If the aggregation is manually configured, this Key value will be a value assigned by the local System.
	//                 range of type : 16-bit
	PartnerOperKey int32 `json:"partner-oper-key,omitempty"`

	// See 802.1AX:
	//                 A MAC address consisting of the unique identifier for the current protocol Partner of this Aggregator. A value of zero indicates that there is no known Partner. If the aggregation is manually configured, this System ID value will be a value assigned by the local System.
	PartnerSystemID string `json:"partner-system-id,omitempty"`

	// See 802.1AX:
	//                 Indicates the priority associated with the Partners System ID. If the aggregation is manually configured, this System Priority value will be a value assigned by the local System.
	//                 range of type : 2-octet
	PartnerSystemPriority int32 `json:"partner-system-priority,omitempty"`
}

// Validate validates this tapi eth eth ctp pac
func (m *TapiEthEthCtpPac) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthCtpCommonPac(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthCtpPac) validateEthCtpCommonPac(formats strfmt.Registry) error {

	if swag.IsZero(m.EthCtpCommonPac) { // not required
		return nil
	}

	if m.EthCtpCommonPac != nil {
		if err := m.EthCtpCommonPac.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-ctp-common-pac")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthCtpPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthCtpPac) UnmarshalBinary(b []byte) error {
	var res TapiEthEthCtpPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
