// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOduEndPointAugmentation1 tapi odu end point augmentation1
// swagger:model tapi.odu.EndPointAugmentation1
type TapiOduEndPointAugmentation1 struct {

	// none
	OduConnectivityServiceEndPointSpec *TapiOduOduConnectivityServiceEndPointSpec `json:"odu-connectivity-service-end-point-spec,omitempty"`
}

// Validate validates this tapi odu end point augmentation1
func (m *TapiOduEndPointAugmentation1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOduConnectivityServiceEndPointSpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOduEndPointAugmentation1) validateOduConnectivityServiceEndPointSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.OduConnectivityServiceEndPointSpec) { // not required
		return nil
	}

	if m.OduConnectivityServiceEndPointSpec != nil {
		if err := m.OduConnectivityServiceEndPointSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-connectivity-service-end-point-spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOduEndPointAugmentation1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOduEndPointAugmentation1) UnmarshalBinary(b []byte) error {
	var res TapiOduEndPointAugmentation1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
