// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiConnectivityDeleteconnectivityserviceInput tapi connectivity deleteconnectivityservice input
// swagger:model tapi.connectivity.deleteconnectivityservice.Input
type TapiConnectivityDeleteconnectivityserviceInput struct {

	// none
	ServiceIDOrName string `json:"service-id-or-name,omitempty"`
}

// Validate validates this tapi connectivity deleteconnectivityservice input
func (m *TapiConnectivityDeleteconnectivityserviceInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityDeleteconnectivityserviceInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityDeleteconnectivityserviceInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityDeleteconnectivityserviceInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
