// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPhotonicMediaOtsiServerAdaptationPac tapi photonic media otsi server adaptation pac
// swagger:model tapi.photonic.media.OtsiServerAdaptationPac
type TapiPhotonicMediaOtsiServerAdaptationPac struct {

	// none
	FecParameters *TapiPhotonicMediaFecProperties `json:"fec-parameters,omitempty"`

	// none
	NumberOfOtsi int32 `json:"number-of-otsi,omitempty"`
}

// Validate validates this tapi photonic media otsi server adaptation pac
func (m *TapiPhotonicMediaOtsiServerAdaptationPac) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFecParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPhotonicMediaOtsiServerAdaptationPac) validateFecParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.FecParameters) { // not required
		return nil
	}

	if m.FecParameters != nil {
		if err := m.FecParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fec-parameters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPhotonicMediaOtsiServerAdaptationPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPhotonicMediaOtsiServerAdaptationPac) UnmarshalBinary(b []byte) error {
	var res TapiPhotonicMediaOtsiServerAdaptationPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
