// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiOamPmParameterValue tapi oam pm parameter value
// swagger:model tapi.oam.PmParameterValue
type TapiOamPmParameterValue struct {

	// none
	PmParameterIntValue int32 `json:"pm-parameter-int-value,omitempty"`

	// none
	PmParameterRealValue string `json:"pm-parameter-real-value,omitempty"`
}

// Validate validates this tapi oam pm parameter value
func (m *TapiOamPmParameterValue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamPmParameterValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamPmParameterValue) UnmarshalBinary(b []byte) error {
	var res TapiOamPmParameterValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
