// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamHistoryData tapi oam history data
// swagger:model tapi.oam.HistoryData
type TapiOamHistoryData struct {
	TapiCommonLocalClass

	// none
	PeriodEndTime string `json:"period-end-time,omitempty"`

	// This attribute indicates the start of the monitoring interval.
	//                 The value is bound to the quarter of an hour in case of a 15 minute interval and bound to the hour in case of a 24 hour interval.
	PeriodStartTime string `json:"period-start-time,omitempty"`

	// none
	PmDataPac *TapiOamPmDataPac `json:"pm-data-pac,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiOamHistoryData) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiCommonLocalClass
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiCommonLocalClass = aO0

	// AO1
	var dataAO1 struct {
		PeriodEndTime string `json:"period-end-time,omitempty"`

		PeriodStartTime string `json:"period-start-time,omitempty"`

		PmDataPac *TapiOamPmDataPac `json:"pm-data-pac,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.PeriodEndTime = dataAO1.PeriodEndTime

	m.PeriodStartTime = dataAO1.PeriodStartTime

	m.PmDataPac = dataAO1.PmDataPac

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiOamHistoryData) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.TapiCommonLocalClass)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		PeriodEndTime string `json:"period-end-time,omitempty"`

		PeriodStartTime string `json:"period-start-time,omitempty"`

		PmDataPac *TapiOamPmDataPac `json:"pm-data-pac,omitempty"`
	}

	dataAO1.PeriodEndTime = m.PeriodEndTime

	dataAO1.PeriodStartTime = m.PeriodStartTime

	dataAO1.PmDataPac = m.PmDataPac

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi oam history data
func (m *TapiOamHistoryData) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiCommonLocalClass
	if err := m.TapiCommonLocalClass.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePmDataPac(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamHistoryData) validatePmDataPac(formats strfmt.Registry) error {

	if swag.IsZero(m.PmDataPac) { // not required
		return nil
	}

	if m.PmDataPac != nil {
		if err := m.PmDataPac.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pm-data-pac")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamHistoryData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamHistoryData) UnmarshalBinary(b []byte) error {
	var res TapiOamHistoryData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
