// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthSamplesDmPerformanceParameters tapi eth samples dm performance parameters
// swagger:model tapi.eth.SamplesDmPerformanceParameters
type TapiEthSamplesDmPerformanceParameters struct {

	// This attribute contains the frame delays measured in ns (nano second, 1x10e-9 seconds). The multiplicity is defined by the numberOfSamples attribute.
	FrameDelayList []int32 `json:"frame-delay-list"`

	// This attribute contains the frame delay variations measured in ns (nano second).  The multiplicity is defined by (numberOfSamples - 1, for numberOfSamples > 0).
	FrameDelayVariationList []int32 `json:"frame-delay-variation-list"`

	// This attribute contains the number of received DM frames (successful samples) used for this frame delay measurement.
	//                 range of type : non-negative
	NumberOfSamples int32 `json:"number-of-samples,omitempty"`
}

// Validate validates this tapi eth samples dm performance parameters
func (m *TapiEthSamplesDmPerformanceParameters) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthSamplesDmPerformanceParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthSamplesDmPerformanceParameters) UnmarshalBinary(b []byte) error {
	var res TapiEthSamplesDmPerformanceParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
