// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamGetoamjobOutputOamJob tapi oam getoamjob output oam job
// swagger:model tapi.oam.getoamjob.output.OamJob
type TapiOamGetoamjobOutputOamJob struct {
	TapiEthOamJobAugmentation1

	TapiEthOamJobAugmentation2

	TapiEthOamJobAugmentation3

	TapiEthOamJobAugmentation4

	TapiEthOamJobAugmentation5

	TapiEthOamJobAugmentation6

	TapiEthOamJobAugmentation7

	TapiOamOamJob
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiOamGetoamjobOutputOamJob) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiEthOamJobAugmentation1
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiEthOamJobAugmentation1 = aO0

	// AO1
	var aO1 TapiEthOamJobAugmentation2
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.TapiEthOamJobAugmentation2 = aO1

	// AO2
	var aO2 TapiEthOamJobAugmentation3
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.TapiEthOamJobAugmentation3 = aO2

	// AO3
	var aO3 TapiEthOamJobAugmentation4
	if err := swag.ReadJSON(raw, &aO3); err != nil {
		return err
	}
	m.TapiEthOamJobAugmentation4 = aO3

	// AO4
	var aO4 TapiEthOamJobAugmentation5
	if err := swag.ReadJSON(raw, &aO4); err != nil {
		return err
	}
	m.TapiEthOamJobAugmentation5 = aO4

	// AO5
	var aO5 TapiEthOamJobAugmentation6
	if err := swag.ReadJSON(raw, &aO5); err != nil {
		return err
	}
	m.TapiEthOamJobAugmentation6 = aO5

	// AO6
	var aO6 TapiEthOamJobAugmentation7
	if err := swag.ReadJSON(raw, &aO6); err != nil {
		return err
	}
	m.TapiEthOamJobAugmentation7 = aO6

	// AO7
	var aO7 TapiOamOamJob
	if err := swag.ReadJSON(raw, &aO7); err != nil {
		return err
	}
	m.TapiOamOamJob = aO7

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiOamGetoamjobOutputOamJob) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 8)

	aO0, err := swag.WriteJSON(m.TapiEthOamJobAugmentation1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.TapiEthOamJobAugmentation2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.TapiEthOamJobAugmentation3)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)

	aO3, err := swag.WriteJSON(m.TapiEthOamJobAugmentation4)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO3)

	aO4, err := swag.WriteJSON(m.TapiEthOamJobAugmentation5)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO4)

	aO5, err := swag.WriteJSON(m.TapiEthOamJobAugmentation6)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO5)

	aO6, err := swag.WriteJSON(m.TapiEthOamJobAugmentation7)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO6)

	aO7, err := swag.WriteJSON(m.TapiOamOamJob)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO7)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi oam getoamjob output oam job
func (m *TapiOamGetoamjobOutputOamJob) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiEthOamJobAugmentation1
	if err := m.TapiEthOamJobAugmentation1.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthOamJobAugmentation2
	if err := m.TapiEthOamJobAugmentation2.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthOamJobAugmentation3
	if err := m.TapiEthOamJobAugmentation3.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthOamJobAugmentation4
	if err := m.TapiEthOamJobAugmentation4.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthOamJobAugmentation5
	if err := m.TapiEthOamJobAugmentation5.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthOamJobAugmentation6
	if err := m.TapiEthOamJobAugmentation6.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEthOamJobAugmentation7
	if err := m.TapiEthOamJobAugmentation7.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiOamOamJob
	if err := m.TapiOamOamJob.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetoamjobOutputOamJob) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetoamjobOutputOamJob) UnmarshalBinary(b []byte) error {
	var res TapiOamGetoamjobOutputOamJob
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
