// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEquipmentPhysicalSpanRef tapi equipment physical span ref
// swagger:model tapi.equipment.PhysicalSpanRef
type TapiEquipmentPhysicalSpanRef struct {

	// none
	PhysicalSpanUUID string `json:"physical-span-uuid,omitempty"`
}

// Validate validates this tapi equipment physical span ref
func (m *TapiEquipmentPhysicalSpanRef) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentPhysicalSpanRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentPhysicalSpanRef) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentPhysicalSpanRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
