// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiOduTcmExtension tapi odu tcm extension
// swagger:model tapi.odu.TcmExtension
type TapiOduTcmExtension string

const (

	// TapiOduTcmExtensionNORMAL captures enum value "NORMAL"
	TapiOduTcmExtensionNORMAL TapiOduTcmExtension = "NORMAL"

	// TapiOduTcmExtensionPASSTHROUGH captures enum value "PASS-THROUGH"
	TapiOduTcmExtensionPASSTHROUGH TapiOduTcmExtension = "PASS-THROUGH"

	// TapiOduTcmExtensionERASE captures enum value "ERASE"
	TapiOduTcmExtensionERASE TapiOduTcmExtension = "ERASE"
)

// for schema
var tapiOduTcmExtensionEnum []interface{}

func init() {
	var res []TapiOduTcmExtension
	if err := json.Unmarshal([]byte(`["NORMAL","PASS-THROUGH","ERASE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiOduTcmExtensionEnum = append(tapiOduTcmExtensionEnum, v)
	}
}

func (m TapiOduTcmExtension) validateTapiOduTcmExtensionEnum(path, location string, value TapiOduTcmExtension) error {
	if err := validate.Enum(path, location, value, tapiOduTcmExtensionEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi odu tcm extension
func (m TapiOduTcmExtension) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiOduTcmExtensionEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
