// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyTopologyNode tapi topology topology node
// swagger:model tapi.topology.topology.Node
type TapiTopologyTopologyNode struct {
	TapiCommonAdminStatePac

	TapiCommonCapacityPac

	TapiCommonGlobalClass

	TapiEquipmentNodeAugmentation1

	TapiTopologyTransferCostPac

	TapiTopologyTransferIntegrityPac

	TapiTopologyTransferTimingPac

	// none
	AggregatedNodeEdgePoint []*TapiTopologyNodeEdgePointRef `json:"aggregated-node-edge-point"`

	// none
	EncapTopology *TapiTopologyTopologyRef `json:"encap-topology,omitempty"`

	// none
	LayerProtocolName []TapiCommonLayerProtocolName `json:"layer-protocol-name"`

	// none
	NodeEdgePoint []*TapiTopologyNodeNodeEdgePoint `json:"node-edge-point"`

	// none
	NodeRuleGroup []*TapiTopologyNodeRuleGroup `json:"node-rule-group"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiTopologyTopologyNode) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiCommonAdminStatePac
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiCommonAdminStatePac = aO0

	// AO1
	var aO1 TapiCommonCapacityPac
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.TapiCommonCapacityPac = aO1

	// AO2
	var aO2 TapiCommonGlobalClass
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.TapiCommonGlobalClass = aO2

	// AO3
	var aO3 TapiEquipmentNodeAugmentation1
	if err := swag.ReadJSON(raw, &aO3); err != nil {
		return err
	}
	m.TapiEquipmentNodeAugmentation1 = aO3

	// AO4
	var aO4 TapiTopologyTransferCostPac
	if err := swag.ReadJSON(raw, &aO4); err != nil {
		return err
	}
	m.TapiTopologyTransferCostPac = aO4

	// AO5
	var aO5 TapiTopologyTransferIntegrityPac
	if err := swag.ReadJSON(raw, &aO5); err != nil {
		return err
	}
	m.TapiTopologyTransferIntegrityPac = aO5

	// AO6
	var aO6 TapiTopologyTransferTimingPac
	if err := swag.ReadJSON(raw, &aO6); err != nil {
		return err
	}
	m.TapiTopologyTransferTimingPac = aO6

	// AO7
	var dataAO7 struct {
		AggregatedNodeEdgePoint []*TapiTopologyNodeEdgePointRef `json:"aggregated-node-edge-point"`

		EncapTopology *TapiTopologyTopologyRef `json:"encap-topology,omitempty"`

		LayerProtocolName []TapiCommonLayerProtocolName `json:"layer-protocol-name"`

		NodeEdgePoint []*TapiTopologyNodeNodeEdgePoint `json:"node-edge-point"`

		NodeRuleGroup []*TapiTopologyNodeRuleGroup `json:"node-rule-group"`
	}
	if err := swag.ReadJSON(raw, &dataAO7); err != nil {
		return err
	}

	m.AggregatedNodeEdgePoint = dataAO7.AggregatedNodeEdgePoint

	m.EncapTopology = dataAO7.EncapTopology

	m.LayerProtocolName = dataAO7.LayerProtocolName

	m.NodeEdgePoint = dataAO7.NodeEdgePoint

	m.NodeRuleGroup = dataAO7.NodeRuleGroup

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiTopologyTopologyNode) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 8)

	aO0, err := swag.WriteJSON(m.TapiCommonAdminStatePac)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.TapiCommonCapacityPac)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.TapiCommonGlobalClass)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)

	aO3, err := swag.WriteJSON(m.TapiEquipmentNodeAugmentation1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO3)

	aO4, err := swag.WriteJSON(m.TapiTopologyTransferCostPac)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO4)

	aO5, err := swag.WriteJSON(m.TapiTopologyTransferIntegrityPac)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO5)

	aO6, err := swag.WriteJSON(m.TapiTopologyTransferTimingPac)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO6)

	var dataAO7 struct {
		AggregatedNodeEdgePoint []*TapiTopologyNodeEdgePointRef `json:"aggregated-node-edge-point"`

		EncapTopology *TapiTopologyTopologyRef `json:"encap-topology,omitempty"`

		LayerProtocolName []TapiCommonLayerProtocolName `json:"layer-protocol-name"`

		NodeEdgePoint []*TapiTopologyNodeNodeEdgePoint `json:"node-edge-point"`

		NodeRuleGroup []*TapiTopologyNodeRuleGroup `json:"node-rule-group"`
	}

	dataAO7.AggregatedNodeEdgePoint = m.AggregatedNodeEdgePoint

	dataAO7.EncapTopology = m.EncapTopology

	dataAO7.LayerProtocolName = m.LayerProtocolName

	dataAO7.NodeEdgePoint = m.NodeEdgePoint

	dataAO7.NodeRuleGroup = m.NodeRuleGroup

	jsonDataAO7, errAO7 := swag.WriteJSON(dataAO7)
	if errAO7 != nil {
		return nil, errAO7
	}
	_parts = append(_parts, jsonDataAO7)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi topology topology node
func (m *TapiTopologyTopologyNode) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiCommonAdminStatePac
	if err := m.TapiCommonAdminStatePac.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiCommonCapacityPac
	if err := m.TapiCommonCapacityPac.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiCommonGlobalClass
	if err := m.TapiCommonGlobalClass.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiEquipmentNodeAugmentation1
	if err := m.TapiEquipmentNodeAugmentation1.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiTopologyTransferCostPac
	if err := m.TapiTopologyTransferCostPac.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiTopologyTransferIntegrityPac
	if err := m.TapiTopologyTransferIntegrityPac.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiTopologyTransferTimingPac
	if err := m.TapiTopologyTransferTimingPac.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAggregatedNodeEdgePoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEncapTopology(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLayerProtocolName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeEdgePoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeRuleGroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyTopologyNode) validateAggregatedNodeEdgePoint(formats strfmt.Registry) error {

	if swag.IsZero(m.AggregatedNodeEdgePoint) { // not required
		return nil
	}

	for i := 0; i < len(m.AggregatedNodeEdgePoint); i++ {
		if swag.IsZero(m.AggregatedNodeEdgePoint[i]) { // not required
			continue
		}

		if m.AggregatedNodeEdgePoint[i] != nil {
			if err := m.AggregatedNodeEdgePoint[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("aggregated-node-edge-point" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiTopologyTopologyNode) validateEncapTopology(formats strfmt.Registry) error {

	if swag.IsZero(m.EncapTopology) { // not required
		return nil
	}

	if m.EncapTopology != nil {
		if err := m.EncapTopology.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("encap-topology")
			}
			return err
		}
	}

	return nil
}

func (m *TapiTopologyTopologyNode) validateLayerProtocolName(formats strfmt.Registry) error {

	if swag.IsZero(m.LayerProtocolName) { // not required
		return nil
	}

	for i := 0; i < len(m.LayerProtocolName); i++ {

		if err := m.LayerProtocolName[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("layer-protocol-name" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *TapiTopologyTopologyNode) validateNodeEdgePoint(formats strfmt.Registry) error {

	if swag.IsZero(m.NodeEdgePoint) { // not required
		return nil
	}

	for i := 0; i < len(m.NodeEdgePoint); i++ {
		if swag.IsZero(m.NodeEdgePoint[i]) { // not required
			continue
		}

		if m.NodeEdgePoint[i] != nil {
			if err := m.NodeEdgePoint[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("node-edge-point" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiTopologyTopologyNode) validateNodeRuleGroup(formats strfmt.Registry) error {

	if swag.IsZero(m.NodeRuleGroup) { // not required
		return nil
	}

	for i := 0; i < len(m.NodeRuleGroup); i++ {
		if swag.IsZero(m.NodeRuleGroup[i]) { // not required
			continue
		}

		if m.NodeRuleGroup[i] != nil {
			if err := m.NodeRuleGroup[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("node-rule-group" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyTopologyNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyTopologyNode) UnmarshalBinary(b []byte) error {
	var res TapiTopologyTopologyNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
