// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPhotonicMediaEndPointAugmentation3 tapi photonic media end point augmentation3
// swagger:model tapi.photonic.media.EndPointAugmentation3
type TapiPhotonicMediaEndPointAugmentation3 struct {

	// none
	MediaChannelConnectivityServiceEndPointSpec *TapiPhotonicMediaMediaChannelConnectivityServiceEndPointSpec `json:"media-channel-connectivity-service-end-point-spec,omitempty"`
}

// Validate validates this tapi photonic media end point augmentation3
func (m *TapiPhotonicMediaEndPointAugmentation3) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMediaChannelConnectivityServiceEndPointSpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPhotonicMediaEndPointAugmentation3) validateMediaChannelConnectivityServiceEndPointSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.MediaChannelConnectivityServiceEndPointSpec) { // not required
		return nil
	}

	if m.MediaChannelConnectivityServiceEndPointSpec != nil {
		if err := m.MediaChannelConnectivityServiceEndPointSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("media-channel-connectivity-service-end-point-spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPhotonicMediaEndPointAugmentation3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPhotonicMediaEndPointAugmentation3) UnmarshalBinary(b []byte) error {
	var res TapiPhotonicMediaEndPointAugmentation3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
