// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthOamServicePointAugmentation2 tapi eth oam service point augmentation2
// swagger:model tapi.eth.OamServicePointAugmentation2
type TapiEthOamServicePointAugmentation2 struct {

	// none
	EthOamMepServicePoint *TapiEthEthOamMepServicePoint `json:"eth-oam-mep-service-point,omitempty"`
}

// Validate validates this tapi eth oam service point augmentation2
func (m *TapiEthOamServicePointAugmentation2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthOamMepServicePoint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthOamServicePointAugmentation2) validateEthOamMepServicePoint(formats strfmt.Registry) error {

	if swag.IsZero(m.EthOamMepServicePoint) { // not required
		return nil
	}

	if m.EthOamMepServicePoint != nil {
		if err := m.EthOamMepServicePoint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-oam-mep-service-point")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthOamServicePointAugmentation2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthOamServicePointAugmentation2) UnmarshalBinary(b []byte) error {
	var res TapiEthOamServicePointAugmentation2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
