// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthProActive1LmPerformanceData tapi eth eth pro active1 lm performance data
// swagger:model tapi.eth.EthProActive1LmPerformanceData
type TapiEthEthProActive1LmPerformanceData struct {

	// This attribute contains the statistical near end performnace parameters.
	StatisticalNearEnd1LmParameters *TapiEthStatisticalLmPerformanceParameters `json:"statistical-near-end-1-lm-parameters,omitempty"`

	// This attribute contains the results of an on-demand synthetic loss measurement job in the ingress direction.
	TotalCountersNearEnd1LmParameters *TapiEthTotalCountersLmPerformanceParameters `json:"total-counters-near-end-1-lm-parameters,omitempty"`
}

// Validate validates this tapi eth eth pro active1 lm performance data
func (m *TapiEthEthProActive1LmPerformanceData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatisticalNearEnd1LmParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalCountersNearEnd1LmParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthProActive1LmPerformanceData) validateStatisticalNearEnd1LmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.StatisticalNearEnd1LmParameters) { // not required
		return nil
	}

	if m.StatisticalNearEnd1LmParameters != nil {
		if err := m.StatisticalNearEnd1LmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("statistical-near-end-1-lm-parameters")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthProActive1LmPerformanceData) validateTotalCountersNearEnd1LmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalCountersNearEnd1LmParameters) { // not required
		return nil
	}

	if m.TotalCountersNearEnd1LmParameters != nil {
		if err := m.TotalCountersNearEnd1LmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("total-counters-near-end-1-lm-parameters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthProActive1LmPerformanceData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthProActive1LmPerformanceData) UnmarshalBinary(b []byte) error {
	var res TapiEthEthProActive1LmPerformanceData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
