// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// TapiEthEthOnDemand1DmSourcePerformanceData tapi eth eth on demand1 dm source performance data
// swagger:model tapi.eth.EthOnDemand1DmSourcePerformanceData
type TapiEthEthOnDemand1DmSourcePerformanceData interface{}
