// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthPriorityMapping tapi eth priority mapping
// swagger:model tapi.eth.PriorityMapping
type TapiEthPriorityMapping struct {

	// This attribute defines the new priority value for the old priority value 0.
	Priority0 int32 `json:"priority-0,omitempty"`

	// This attribute defines the new priority value for the old priority value 1.
	Priority1 *int32 `json:"priority-1,omitempty"`

	// This attribute defines the new priority value for the old priority value 2.
	Priority2 *int32 `json:"priority-2,omitempty"`

	// This attribute defines the new priority value for the old priority value 3.
	Priority3 *int32 `json:"priority-3,omitempty"`

	// This attribute defines the new priority value for the old priority value 4.
	Priority4 *int32 `json:"priority-4,omitempty"`

	// This attribute defines the new priority value for the old priority value 5.
	Priority5 *int32 `json:"priority-5,omitempty"`

	// This attribute defines the new priority value for the old priority value 6.
	Priority6 *int32 `json:"priority-6,omitempty"`

	// This attribute defines the new priority value for the old priority value 7.
	Priority7 *int32 `json:"priority-7,omitempty"`
}

// Validate validates this tapi eth priority mapping
func (m *TapiEthPriorityMapping) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthPriorityMapping) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthPriorityMapping) UnmarshalBinary(b []byte) error {
	var res TapiEthPriorityMapping
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
