// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamGetoamservicelistOutput tapi oam getoamservicelist output
// swagger:model tapi.oam.getoamservicelist.Output
type TapiOamGetoamservicelistOutput struct {

	// none
	OamService []*TapiOamGetoamservicelistOutputOamService `json:"oam-service"`
}

// Validate validates this tapi oam getoamservicelist output
func (m *TapiOamGetoamservicelistOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOamService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamGetoamservicelistOutput) validateOamService(formats strfmt.Registry) error {

	if swag.IsZero(m.OamService) { // not required
		return nil
	}

	for i := 0; i < len(m.OamService); i++ {
		if swag.IsZero(m.OamService[i]) { // not required
			continue
		}

		if m.OamService[i] != nil {
			if err := m.OamService[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("oam-service" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetoamservicelistOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetoamservicelistOutput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetoamservicelistOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
