// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiOduTcmMode tapi odu tcm mode
// swagger:model tapi.odu.TcmMode
type TapiOduTcmMode string

const (

	// TapiOduTcmModeOPERATIONAL captures enum value "OPERATIONAL"
	TapiOduTcmModeOPERATIONAL TapiOduTcmMode = "OPERATIONAL"

	// TapiOduTcmModeTRANSPARENT captures enum value "TRANSPARENT"
	TapiOduTcmModeTRANSPARENT TapiOduTcmMode = "TRANSPARENT"

	// TapiOduTcmModeMONITOR captures enum value "MONITOR"
	TapiOduTcmModeMONITOR TapiOduTcmMode = "MONITOR"
)

// for schema
var tapiOduTcmModeEnum []interface{}

func init() {
	var res []TapiOduTcmMode
	if err := json.Unmarshal([]byte(`["OPERATIONAL","TRANSPARENT","MONITOR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiOduTcmModeEnum = append(tapiOduTcmModeEnum, v)
	}
}

func (m TapiOduTcmMode) validateTapiOduTcmModeEnum(path, location string, value TapiOduTcmMode) error {
	if err := validate.Enum(path, location, value, tapiOduTcmModeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi odu tcm mode
func (m TapiOduTcmMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiOduTcmModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
