// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityUpdateconnectivityserviceOutput tapi connectivity updateconnectivityservice output
// swagger:model tapi.connectivity.updateconnectivityservice.Output
type TapiConnectivityUpdateconnectivityserviceOutput struct {

	// none
	Service *TapiConnectivityUpdateconnectivityserviceOutputService `json:"service,omitempty"`
}

// Validate validates this tapi connectivity updateconnectivityservice output
func (m *TapiConnectivityUpdateconnectivityserviceOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityUpdateconnectivityserviceOutput) validateService(formats strfmt.Registry) error {

	if swag.IsZero(m.Service) { // not required
		return nil
	}

	if m.Service != nil {
		if err := m.Service.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("service")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityUpdateconnectivityserviceOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityUpdateconnectivityserviceOutput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityUpdateconnectivityserviceOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
