// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiPhotonicMediaFecProperties tapi photonic media fec properties
// swagger:model tapi.photonic.media.FecProperties
type TapiPhotonicMediaFecProperties struct {

	// Bits corrected between those that were received corrupted
	CorrectedBits int32 `json:"corrected-bits,omitempty"`

	// Bytes corrected between those that were received corrupted
	CorrectedBytes int32 `json:"corrected-bytes,omitempty"`

	// counter: bit error rate after correction by FEC
	PostFecBer int32 `json:"post-fec-ber,omitempty"`

	// counter: bit error rate before correction by FEC
	PreFecBer int32 `json:"pre-fec-ber,omitempty"`

	// Bits that could not be corrected by FEC
	UncorrectableBits int32 `json:"uncorrectable-bits,omitempty"`

	// Bytes that could not be corrected by FEC
	UncorrectableBytes int32 `json:"uncorrectable-bytes,omitempty"`
}

// Validate validates this tapi photonic media fec properties
func (m *TapiPhotonicMediaFecProperties) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiPhotonicMediaFecProperties) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPhotonicMediaFecProperties) UnmarshalBinary(b []byte) error {
	var res TapiPhotonicMediaFecProperties
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
