// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// TapiEthEthOnDemand1LmSourcePerformanceData tapi eth eth on demand1 lm source performance data
// swagger:model tapi.eth.EthOnDemand1LmSourcePerformanceData
type TapiEthEthOnDemand1LmSourcePerformanceData interface{}
