// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiNotificationGetnotificationsubscriptionservicedetailsInput tapi notification getnotificationsubscriptionservicedetails input
// swagger:model tapi.notification.getnotificationsubscriptionservicedetails.Input
type TapiNotificationGetnotificationsubscriptionservicedetailsInput struct {

	// none
	SubscriptionIDOrName string `json:"subscription-id-or-name,omitempty"`
}

// Validate validates this tapi notification getnotificationsubscriptionservicedetails input
func (m *TapiNotificationGetnotificationsubscriptionservicedetailsInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiNotificationGetnotificationsubscriptionservicedetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNotificationGetnotificationsubscriptionservicedetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiNotificationGetnotificationsubscriptionservicedetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
