// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthOamJobAugmentation4 tapi eth oam job augmentation4
// swagger:model tapi.eth.OamJobAugmentation4
type TapiEthOamJobAugmentation4 struct {

	// none
	EthProActiveDualEndedMeasurementJob *TapiEthEthProActiveDualEndedMeasurementJob `json:"eth-pro-active-dual-ended-measurement-job,omitempty"`
}

// Validate validates this tapi eth oam job augmentation4
func (m *TapiEthOamJobAugmentation4) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthProActiveDualEndedMeasurementJob(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthOamJobAugmentation4) validateEthProActiveDualEndedMeasurementJob(formats strfmt.Registry) error {

	if swag.IsZero(m.EthProActiveDualEndedMeasurementJob) { // not required
		return nil
	}

	if m.EthProActiveDualEndedMeasurementJob != nil {
		if err := m.EthProActiveDualEndedMeasurementJob.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-pro-active-dual-ended-measurement-job")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthOamJobAugmentation4) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthOamJobAugmentation4) UnmarshalBinary(b []byte) error {
	var res TapiEthOamJobAugmentation4
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
