// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiVirtualNetworkGetvirtualnetworkservicedetailsInput tapi virtual network getvirtualnetworkservicedetails input
// swagger:model tapi.virtual.network.getvirtualnetworkservicedetails.Input
type TapiVirtualNetworkGetvirtualnetworkservicedetailsInput struct {

	// none
	ServiceIDOrName string `json:"service-id-or-name,omitempty"`
}

// Validate validates this tapi virtual network getvirtualnetworkservicedetails input
func (m *TapiVirtualNetworkGetvirtualnetworkservicedetailsInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiVirtualNetworkGetvirtualnetworkservicedetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiVirtualNetworkGetvirtualnetworkservicedetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiVirtualNetworkGetvirtualnetworkservicedetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
