// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEquipmentGetphysicalspanOutput tapi equipment getphysicalspan output
// swagger:model tapi.equipment.getphysicalspan.Output
type TapiEquipmentGetphysicalspanOutput struct {

	// none
	PhysicalSpan *TapiEquipmentPhysicalSpan `json:"physical-span,omitempty"`
}

// Validate validates this tapi equipment getphysicalspan output
func (m *TapiEquipmentGetphysicalspanOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePhysicalSpan(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEquipmentGetphysicalspanOutput) validatePhysicalSpan(formats strfmt.Registry) error {

	if swag.IsZero(m.PhysicalSpan) { // not required
		return nil
	}

	if m.PhysicalSpan != nil {
		if err := m.PhysicalSpan.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("physical-span")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentGetphysicalspanOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentGetphysicalspanOutput) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentGetphysicalspanOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
