// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEquipmentActualHolder tapi equipment actual holder
// swagger:model tapi.equipment.ActualHolder
type TapiEquipmentActualHolder struct {

	// none
	CommonHolderProperties *TapiEquipmentCommonHolderProperties `json:"common-holder-properties,omitempty"`
}

// Validate validates this tapi equipment actual holder
func (m *TapiEquipmentActualHolder) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommonHolderProperties(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEquipmentActualHolder) validateCommonHolderProperties(formats strfmt.Registry) error {

	if swag.IsZero(m.CommonHolderProperties) { // not required
		return nil
	}

	if m.CommonHolderProperties != nil {
		if err := m.CommonHolderProperties.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("common-holder-properties")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentActualHolder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentActualHolder) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentActualHolder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
