// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamNotificationAugmentation1 tapi oam notification augmentation1
// swagger:model tapi.oam.NotificationAugmentation1
type TapiOamNotificationAugmentation1 struct {

	// none
	AlarmInfo *TapiOamAlarmInfo `json:"alarm-info,omitempty"`
}

// Validate validates this tapi oam notification augmentation1
func (m *TapiOamNotificationAugmentation1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlarmInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamNotificationAugmentation1) validateAlarmInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.AlarmInfo) { // not required
		return nil
	}

	if m.AlarmInfo != nil {
		if err := m.AlarmInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("alarm-info")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamNotificationAugmentation1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamNotificationAugmentation1) UnmarshalBinary(b []byte) error {
	var res TapiOamNotificationAugmentation1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
