// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiOamGetmegInput tapi oam getmeg input
// swagger:model tapi.oam.getmeg.Input
type TapiOamGetmegInput struct {

	// none
	OamServiceID string `json:"oam-service-id,omitempty"`
}

// Validate validates this tapi oam getmeg input
func (m *TapiOamGetmegInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetmegInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetmegInput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetmegInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
