// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiOamGetoamserviceInput tapi oam getoamservice input
// swagger:model tapi.oam.getoamservice.Input
type TapiOamGetoamserviceInput struct {

	// none
	OamServiceID string `json:"oam-service-id,omitempty"`
}

// Validate validates this tapi oam getoamservice input
func (m *TapiOamGetoamserviceInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetoamserviceInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetoamserviceInput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetoamserviceInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
