// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEquipmentExpectedEquipment tapi equipment expected equipment
// swagger:model tapi.equipment.ExpectedEquipment
type TapiEquipmentExpectedEquipment struct {

	// none
	CommonEquipmentProperties *TapiEquipmentCommonEquipmentProperties `json:"common-equipment-properties,omitempty"`

	// none
	ExpectedHolder []*TapiEquipmentExpectedHolder `json:"expected-holder"`

	// none
	ExpectedNonFieldReplaceableModule []*TapiEquipmentExpectedNonFieldReplaceableModule `json:"expected-non-field-replaceable-module"`
}

// Validate validates this tapi equipment expected equipment
func (m *TapiEquipmentExpectedEquipment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommonEquipmentProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpectedHolder(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpectedNonFieldReplaceableModule(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEquipmentExpectedEquipment) validateCommonEquipmentProperties(formats strfmt.Registry) error {

	if swag.IsZero(m.CommonEquipmentProperties) { // not required
		return nil
	}

	if m.CommonEquipmentProperties != nil {
		if err := m.CommonEquipmentProperties.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("common-equipment-properties")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEquipmentExpectedEquipment) validateExpectedHolder(formats strfmt.Registry) error {

	if swag.IsZero(m.ExpectedHolder) { // not required
		return nil
	}

	for i := 0; i < len(m.ExpectedHolder); i++ {
		if swag.IsZero(m.ExpectedHolder[i]) { // not required
			continue
		}

		if m.ExpectedHolder[i] != nil {
			if err := m.ExpectedHolder[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("expected-holder" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiEquipmentExpectedEquipment) validateExpectedNonFieldReplaceableModule(formats strfmt.Registry) error {

	if swag.IsZero(m.ExpectedNonFieldReplaceableModule) { // not required
		return nil
	}

	for i := 0; i < len(m.ExpectedNonFieldReplaceableModule); i++ {
		if swag.IsZero(m.ExpectedNonFieldReplaceableModule[i]) { // not required
			continue
		}

		if m.ExpectedNonFieldReplaceableModule[i] != nil {
			if err := m.ExpectedNonFieldReplaceableModule[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("expected-non-field-replaceable-module" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentExpectedEquipment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentExpectedEquipment) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentExpectedEquipment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
