// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthMaintenanceAssociationName tapi eth maintenance association name
// swagger:model tapi.eth.MaintenanceAssociationName
type TapiEthMaintenanceAssociationName struct {

	// IEEE P802.1Qcx/D0.3:
	//                 MEF 38:
	//                 RFC2579 DisplayString, except that the character codes 0-31 (decimal) are not used.
	//                 Length '1..45'
	CharString string `json:"char-string,omitempty"`

	// IEEE P802.1Qcx/D0.3:
	//                 ICC-based format as specified in ITU-T Y.1731.
	//                 Length '1..45'
	IccFormat string `json:"icc-format,omitempty"`

	// IEEE P802.1Qcx/D0.3:
	//                 Reserved for definition by IEEE 802.1. Recommend not to use zero unless absolutely needed.
	//                 Length '1..45'.
	IeeeReserved *string `json:"ieee-reserved,omitempty"`

	// IEEE P802.1Qcx/D0.3:
	//                 MEF 38:
	//                 Primary VLAN ID. 12 bits represented in a 2-octet integer.
	PrimaryVlanID string `json:"primary-vlan-id,omitempty"`

	// IEEE P802.1Qcx/D0.3:
	//                 MEF 38:
	//                 RFC2685 VPN ID. 3 octet VPN authority Organizationally Unique Identifier followed by 4 octet VPN index identifying VPN according to the OUI.
	//                 Length '1..45';
	Rfc2865VpnID string `json:"rfc-2865-vpn-id,omitempty"`

	// IEEE P802.1Qcx/D0.3:
	//                 MEF 38:
	//                 2-octet integer/big endian.
	UnsignedInt16 int32 `json:"unsigned-int-16,omitempty"`
}

// Validate validates this tapi eth maintenance association name
func (m *TapiEthMaintenanceAssociationName) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthMaintenanceAssociationName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthMaintenanceAssociationName) UnmarshalBinary(b []byte) error {
	var res TapiEthMaintenanceAssociationName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
