// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiOamThresholdCrossingQualifier tapi oam threshold crossing qualifier
// swagger:model tapi.oam.ThresholdCrossingQualifier
type TapiOamThresholdCrossingQualifier string

const (

	// TapiOamThresholdCrossingQualifierNOTAPPLICABLE captures enum value "NOT_APPLICABLE"
	TapiOamThresholdCrossingQualifierNOTAPPLICABLE TapiOamThresholdCrossingQualifier = "NOT_APPLICABLE"

	// TapiOamThresholdCrossingQualifierNEAREND captures enum value "NEAR_END"
	TapiOamThresholdCrossingQualifierNEAREND TapiOamThresholdCrossingQualifier = "NEAR_END"

	// TapiOamThresholdCrossingQualifierFAREND captures enum value "FAR_END"
	TapiOamThresholdCrossingQualifierFAREND TapiOamThresholdCrossingQualifier = "FAR_END"

	// TapiOamThresholdCrossingQualifierBIDIRECTIONAL captures enum value "BIDIRECTIONAL"
	TapiOamThresholdCrossingQualifierBIDIRECTIONAL TapiOamThresholdCrossingQualifier = "BIDIRECTIONAL"

	// TapiOamThresholdCrossingQualifierFORWARD captures enum value "FORWARD"
	TapiOamThresholdCrossingQualifierFORWARD TapiOamThresholdCrossingQualifier = "FORWARD"

	// TapiOamThresholdCrossingQualifierBACKWARD captures enum value "BACKWARD"
	TapiOamThresholdCrossingQualifierBACKWARD TapiOamThresholdCrossingQualifier = "BACKWARD"
)

// for schema
var tapiOamThresholdCrossingQualifierEnum []interface{}

func init() {
	var res []TapiOamThresholdCrossingQualifier
	if err := json.Unmarshal([]byte(`["NOT_APPLICABLE","NEAR_END","FAR_END","BIDIRECTIONAL","FORWARD","BACKWARD"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiOamThresholdCrossingQualifierEnum = append(tapiOamThresholdCrossingQualifierEnum, v)
	}
}

func (m TapiOamThresholdCrossingQualifier) validateTapiOamThresholdCrossingQualifierEnum(path, location string, value TapiOamThresholdCrossingQualifier) error {
	if err := validate.Enum(path, location, value, tapiOamThresholdCrossingQualifierEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi oam threshold crossing qualifier
func (m TapiOamThresholdCrossingQualifier) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiOamThresholdCrossingQualifierEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
