// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthCurrentDataAugmentation8 tapi eth current data augmentation8
// swagger:model tapi.eth.CurrentDataAugmentation8
type TapiEthCurrentDataAugmentation8 struct {

	// none
	EthLoopbackResultData *TapiEthEthLoopbackResultData `json:"eth-loopback-result-data,omitempty"`
}

// Validate validates this tapi eth current data augmentation8
func (m *TapiEthCurrentDataAugmentation8) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthLoopbackResultData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthCurrentDataAugmentation8) validateEthLoopbackResultData(formats strfmt.Registry) error {

	if swag.IsZero(m.EthLoopbackResultData) { // not required
		return nil
	}

	if m.EthLoopbackResultData != nil {
		if err := m.EthLoopbackResultData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-loopback-result-data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthCurrentDataAugmentation8) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthCurrentDataAugmentation8) UnmarshalBinary(b []byte) error {
	var res TapiEthCurrentDataAugmentation8
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
