// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEquipmentCommonHolderProperties tapi equipment common holder properties
// swagger:model tapi.equipment.CommonHolderProperties
type TapiEquipmentCommonHolderProperties struct {

	// The type of holder.
	HolderCategory string `json:"holder-category,omitempty"`

	// The relative position of the holder in the context of its containing equipment along with the position of that containing Equipment (and further recursion).
	HolderLocation string `json:"holder-location,omitempty"`

	// This attribute indicates whether the holder has guides that constrain the position of the equipment in the holder or not.
	IsGUIDED *bool `json:"is-guided,omitempty"`
}

// Validate validates this tapi equipment common holder properties
func (m *TapiEquipmentCommonHolderProperties) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentCommonHolderProperties) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentCommonHolderProperties) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentCommonHolderProperties
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
