// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamGetmegOutput tapi oam getmeg output
// swagger:model tapi.oam.getmeg.Output
type TapiOamGetmegOutput struct {

	// none
	Meg *TapiOamGetmegOutputMeg `json:"meg,omitempty"`
}

// Validate validates this tapi oam getmeg output
func (m *TapiOamGetmegOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMeg(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamGetmegOutput) validateMeg(formats strfmt.Registry) error {

	if swag.IsZero(m.Meg) { // not required
		return nil
	}

	if m.Meg != nil {
		if err := m.Meg.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("meg")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetmegOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetmegOutput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetmegOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
