// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEquipmentDeviceRef tapi equipment device ref
// swagger:model tapi.equipment.DeviceRef
type TapiEquipmentDeviceRef struct {

	// none
	DeviceUUID string `json:"device-uuid,omitempty"`
}

// Validate validates this tapi equipment device ref
func (m *TapiEquipmentDeviceRef) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentDeviceRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentDeviceRef) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentDeviceRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
