// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthCurrentDataAugmentation6 tapi eth current data augmentation6
// swagger:model tapi.eth.CurrentDataAugmentation6
type TapiEthCurrentDataAugmentation6 struct {

	// none
	EthOnDemand1DmSourcePerformanceData TapiEthEthOnDemand1DmSourcePerformanceData `json:"eth-on-demand-1-dm-source-performance-data,omitempty"`
}

// Validate validates this tapi eth current data augmentation6
func (m *TapiEthCurrentDataAugmentation6) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthCurrentDataAugmentation6) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthCurrentDataAugmentation6) UnmarshalBinary(b []byte) error {
	var res TapiEthCurrentDataAugmentation6
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
