// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamUpdateoamprofileInput tapi oam updateoamprofile input
// swagger:model tapi.oam.updateoamprofile.Input
type TapiOamUpdateoamprofileInput struct {

	// none
	OamProfileID string `json:"oam-profile-id,omitempty"`

	// none
	PmThresholdData []*TapiOamPmThresholdData `json:"pm-threshold-data"`
}

// Validate validates this tapi oam updateoamprofile input
func (m *TapiOamUpdateoamprofileInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePmThresholdData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamUpdateoamprofileInput) validatePmThresholdData(formats strfmt.Registry) error {

	if swag.IsZero(m.PmThresholdData) { // not required
		return nil
	}

	for i := 0; i < len(m.PmThresholdData); i++ {
		if swag.IsZero(m.PmThresholdData[i]) { // not required
			continue
		}

		if m.PmThresholdData[i] != nil {
			if err := m.PmThresholdData[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pm-threshold-data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamUpdateoamprofileInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamUpdateoamprofileInput) UnmarshalBinary(b []byte) error {
	var res TapiOamUpdateoamprofileInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
