// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiVirtualNetworkGetvirtualnetworkservicelistOutput tapi virtual network getvirtualnetworkservicelist output
// swagger:model tapi.virtual.network.getvirtualnetworkservicelist.Output
type TapiVirtualNetworkGetvirtualnetworkservicelistOutput struct {

	// none
	Service []*TapiVirtualNetworkVirtualNetworkService `json:"service"`
}

// Validate validates this tapi virtual network getvirtualnetworkservicelist output
func (m *TapiVirtualNetworkGetvirtualnetworkservicelistOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiVirtualNetworkGetvirtualnetworkservicelistOutput) validateService(formats strfmt.Registry) error {

	if swag.IsZero(m.Service) { // not required
		return nil
	}

	for i := 0; i < len(m.Service); i++ {
		if swag.IsZero(m.Service[i]) { // not required
			continue
		}

		if m.Service[i] != nil {
			if err := m.Service[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("service" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiVirtualNetworkGetvirtualnetworkservicelistOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiVirtualNetworkGetvirtualnetworkservicelistOutput) UnmarshalBinary(b []byte) error {
	var res TapiVirtualNetworkGetvirtualnetworkservicelistOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
