// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiConnectivityGetconnectionendpointdetailsInput tapi connectivity getconnectionendpointdetails input
// swagger:model tapi.connectivity.getconnectionendpointdetails.Input
type TapiConnectivityGetconnectionendpointdetailsInput struct {

	// none
	CepIDOrName string `json:"cep-id-or-name,omitempty"`

	// none
	NepIDOrName string `json:"nep-id-or-name,omitempty"`

	// none
	NodeIDOrName string `json:"node-id-or-name,omitempty"`

	// none
	TopologyIDOrName string `json:"topology-id-or-name,omitempty"`
}

// Validate validates this tapi connectivity getconnectionendpointdetails input
func (m *TapiConnectivityGetconnectionendpointdetailsInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityGetconnectionendpointdetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityGetconnectionendpointdetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityGetconnectionendpointdetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
