// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiTopologyGetnodeedgepointdetailsOutput tapi topology getnodeedgepointdetails output
// swagger:model tapi.topology.getnodeedgepointdetails.Output
type TapiTopologyGetnodeedgepointdetailsOutput struct {

	// none
	NodeEdgePoint *TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint `json:"node-edge-point,omitempty"`
}

// Validate validates this tapi topology getnodeedgepointdetails output
func (m *TapiTopologyGetnodeedgepointdetailsOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNodeEdgePoint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiTopologyGetnodeedgepointdetailsOutput) validateNodeEdgePoint(formats strfmt.Registry) error {

	if swag.IsZero(m.NodeEdgePoint) { // not required
		return nil
	}

	if m.NodeEdgePoint != nil {
		if err := m.NodeEdgePoint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node-edge-point")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiTopologyGetnodeedgepointdetailsOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiTopologyGetnodeedgepointdetailsOutput) UnmarshalBinary(b []byte) error {
	var res TapiTopologyGetnodeedgepointdetailsOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
