// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiNotificationGetnotificationsubscriptionservicedetailsOutput tapi notification getnotificationsubscriptionservicedetails output
// swagger:model tapi.notification.getnotificationsubscriptionservicedetails.Output
type TapiNotificationGetnotificationsubscriptionservicedetailsOutput struct {

	// none
	SubscriptionService *TapiNotificationNotificationSubscriptionService `json:"subscription-service,omitempty"`
}

// Validate validates this tapi notification getnotificationsubscriptionservicedetails output
func (m *TapiNotificationGetnotificationsubscriptionservicedetailsOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiNotificationGetnotificationsubscriptionservicedetailsOutput) validateSubscriptionService(formats strfmt.Registry) error {

	if swag.IsZero(m.SubscriptionService) { // not required
		return nil
	}

	if m.SubscriptionService != nil {
		if err := m.SubscriptionService.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("subscription-service")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiNotificationGetnotificationsubscriptionservicedetailsOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNotificationGetnotificationsubscriptionservicedetailsOutput) UnmarshalBinary(b []byte) error {
	var res TapiNotificationGetnotificationsubscriptionservicedetailsOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
