// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEquipmentConnectorPinAddress tapi equipment connector pin address
// swagger:model tapi.equipment.ConnectorPinAddress
type TapiEquipmentConnectorPinAddress struct {

	// Identification of the Connector in the conetxt of the referenced Equipment.
	ConnectorIdentification string `json:"connector-identification,omitempty"`

	// Reference to the Equipment that is fitted with the Connector/Pin.
	EquipmentUUID string `json:"equipment-uuid,omitempty"`

	// Where relevant, identification of the Pin in the contect of the connector.
	//                 Where the whole connector is used, then individual Pins need not be identified.
	PinIdentification string `json:"pin-identification,omitempty"`
}

// Validate validates this tapi equipment connector pin address
func (m *TapiEquipmentConnectorPinAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentConnectorPinAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentConnectorPinAddress) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentConnectorPinAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
