// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList tapi connectivity context topologycontext topology node nodeedgepoint cep list
// swagger:model tapi.connectivity.context.topologycontext.topology.node.nodeedgepoint.CepList
type TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList struct {

	// none
	ConnectionEndPoint []*TapiConnectivityCeplistConnectionEndPoint `json:"connection-end-point"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		ConnectionEndPoint []*TapiConnectivityCeplistConnectionEndPoint `json:"connection-end-point"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.ConnectionEndPoint = dataAO0.ConnectionEndPoint

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		ConnectionEndPoint []*TapiConnectivityCeplistConnectionEndPoint `json:"connection-end-point"`
	}

	dataAO0.ConnectionEndPoint = m.ConnectionEndPoint

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi connectivity context topologycontext topology node nodeedgepoint cep list
func (m *TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectionEndPoint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList) validateConnectionEndPoint(formats strfmt.Registry) error {

	if swag.IsZero(m.ConnectionEndPoint) { // not required
		return nil
	}

	for i := 0; i < len(m.ConnectionEndPoint); i++ {
		if swag.IsZero(m.ConnectionEndPoint[i]) { // not required
			continue
		}

		if m.ConnectionEndPoint[i] != nil {
			if err := m.ConnectionEndPoint[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("connection-end-point" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityContextTopologycontextTopologyNodeNodeedgepointCepList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
