// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamUpdateoamjobOutput tapi oam updateoamjob output
// swagger:model tapi.oam.updateoamjob.Output
type TapiOamUpdateoamjobOutput struct {

	// none
	OamJob *TapiOamGetoamjobOutputOamJob `json:"oam-job,omitempty"`
}

// Validate validates this tapi oam updateoamjob output
func (m *TapiOamUpdateoamjobOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOamJob(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamUpdateoamjobOutput) validateOamJob(formats strfmt.Registry) error {

	if swag.IsZero(m.OamJob) { // not required
		return nil
	}

	if m.OamJob != nil {
		if err := m.OamJob.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("oam-job")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamUpdateoamjobOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamUpdateoamjobOutput) UnmarshalBinary(b []byte) error {
	var res TapiOamUpdateoamjobOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
