// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiNotificationGetsupportednotificationtypesOutput tapi notification getsupportednotificationtypes output
// swagger:model tapi.notification.getsupportednotificationtypes.Output
type TapiNotificationGetsupportednotificationtypesOutput struct {

	// none
	SupportedNotificationTypes []string `json:"supported-notification-types"`

	// none
	SupportedObjectTypes []string `json:"supported-object-types"`
}

// Validate validates this tapi notification getsupportednotificationtypes output
func (m *TapiNotificationGetsupportednotificationtypesOutput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiNotificationGetsupportednotificationtypesOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNotificationGetsupportednotificationtypesOutput) UnmarshalBinary(b []byte) error {
	var res TapiNotificationGetsupportednotificationtypesOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
