// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamConnectionEndPointAugmentation3 tapi oam connection end point augmentation3
// swagger:model tapi.oam.ConnectionEndPointAugmentation3
type TapiOamConnectionEndPointAugmentation3 struct {

	// none
	MepMipList *TapiOamMepMipList `json:"mep-mip-list,omitempty"`
}

// Validate validates this tapi oam connection end point augmentation3
func (m *TapiOamConnectionEndPointAugmentation3) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMepMipList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamConnectionEndPointAugmentation3) validateMepMipList(formats strfmt.Registry) error {

	if swag.IsZero(m.MepMipList) { // not required
		return nil
	}

	if m.MepMipList != nil {
		if err := m.MepMipList.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mep-mip-list")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamConnectionEndPointAugmentation3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamConnectionEndPointAugmentation3) UnmarshalBinary(b []byte) error {
	var res TapiOamConnectionEndPointAugmentation3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
