// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthInputAugmentation5 tapi eth input augmentation5
// swagger:model tapi.eth.InputAugmentation5
type TapiEthInputAugmentation5 struct {

	// none
	EthOnDemandDualEndedMeasurementJob *TapiEthEthOnDemandDualEndedMeasurementJob `json:"eth-on-demand-dual-ended-measurement-job,omitempty"`
}

// Validate validates this tapi eth input augmentation5
func (m *TapiEthInputAugmentation5) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthOnDemandDualEndedMeasurementJob(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthInputAugmentation5) validateEthOnDemandDualEndedMeasurementJob(formats strfmt.Registry) error {

	if swag.IsZero(m.EthOnDemandDualEndedMeasurementJob) { // not required
		return nil
	}

	if m.EthOnDemandDualEndedMeasurementJob != nil {
		if err := m.EthOnDemandDualEndedMeasurementJob.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-on-demand-dual-ended-measurement-job")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthInputAugmentation5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthInputAugmentation5) UnmarshalBinary(b []byte) error {
	var res TapiEthInputAugmentation5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
