// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiOamPerceivedTcaSeverity tapi oam perceived tca severity
// swagger:model tapi.oam.PerceivedTcaSeverity
type TapiOamPerceivedTcaSeverity string

const (

	// TapiOamPerceivedTcaSeverityWARNING captures enum value "WARNING"
	TapiOamPerceivedTcaSeverityWARNING TapiOamPerceivedTcaSeverity = "WARNING"

	// TapiOamPerceivedTcaSeverityCLEAR captures enum value "CLEAR"
	TapiOamPerceivedTcaSeverityCLEAR TapiOamPerceivedTcaSeverity = "CLEAR"
)

// for schema
var tapiOamPerceivedTcaSeverityEnum []interface{}

func init() {
	var res []TapiOamPerceivedTcaSeverity
	if err := json.Unmarshal([]byte(`["WARNING","CLEAR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiOamPerceivedTcaSeverityEnum = append(tapiOamPerceivedTcaSeverityEnum, v)
	}
}

func (m TapiOamPerceivedTcaSeverity) validateTapiOamPerceivedTcaSeverityEnum(path, location string, value TapiOamPerceivedTcaSeverity) error {
	if err := validate.Enum(path, location, value, tapiOamPerceivedTcaSeverityEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi oam perceived tca severity
func (m TapiOamPerceivedTcaSeverity) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiOamPerceivedTcaSeverityEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
