// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthConnectivityServiceEndPointSpec tapi eth eth connectivity service end point spec
// swagger:model tapi.eth.EthConnectivityServiceEndPointSpec
type TapiEthEthConnectivityServiceEndPointSpec struct {

	// none
	EthCtpCommonPac *TapiEthEthCtpCommonPac `json:"eth-ctp-common-pac,omitempty"`

	// none
	EthTerminationCommonPac *TapiEthEthTerminationCommonPac `json:"eth-termination-common-pac,omitempty"`

	// none
	EtyTerminationCommonPac *TapiEthEtyTerminationCommonPac `json:"ety-termination-common-pac,omitempty"`
}

// Validate validates this tapi eth eth connectivity service end point spec
func (m *TapiEthEthConnectivityServiceEndPointSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthCtpCommonPac(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEthTerminationCommonPac(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEtyTerminationCommonPac(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthConnectivityServiceEndPointSpec) validateEthCtpCommonPac(formats strfmt.Registry) error {

	if swag.IsZero(m.EthCtpCommonPac) { // not required
		return nil
	}

	if m.EthCtpCommonPac != nil {
		if err := m.EthCtpCommonPac.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-ctp-common-pac")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthConnectivityServiceEndPointSpec) validateEthTerminationCommonPac(formats strfmt.Registry) error {

	if swag.IsZero(m.EthTerminationCommonPac) { // not required
		return nil
	}

	if m.EthTerminationCommonPac != nil {
		if err := m.EthTerminationCommonPac.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-termination-common-pac")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthConnectivityServiceEndPointSpec) validateEtyTerminationCommonPac(formats strfmt.Registry) error {

	if swag.IsZero(m.EtyTerminationCommonPac) { // not required
		return nil
	}

	if m.EtyTerminationCommonPac != nil {
		if err := m.EtyTerminationCommonPac.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ety-termination-common-pac")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthConnectivityServiceEndPointSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthConnectivityServiceEndPointSpec) UnmarshalBinary(b []byte) error {
	var res TapiEthEthConnectivityServiceEndPointSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
