// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEquipmentNodeAugmentation1 tapi equipment node augmentation1
// swagger:model tapi.equipment.NodeAugmentation1
type TapiEquipmentNodeAugmentation1 struct {

	// none
	SupportingPhysicalSpan *TapiEquipmentSupportingPhysicalSpan `json:"supporting-physical-span,omitempty"`
}

// Validate validates this tapi equipment node augmentation1
func (m *TapiEquipmentNodeAugmentation1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSupportingPhysicalSpan(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEquipmentNodeAugmentation1) validateSupportingPhysicalSpan(formats strfmt.Registry) error {

	if swag.IsZero(m.SupportingPhysicalSpan) { // not required
		return nil
	}

	if m.SupportingPhysicalSpan != nil {
		if err := m.SupportingPhysicalSpan.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("supporting-physical-span")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEquipmentNodeAugmentation1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEquipmentNodeAugmentation1) UnmarshalBinary(b []byte) error {
	var res TapiEquipmentNodeAugmentation1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
